version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "network.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=false"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstashElk
    volumes:
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstashplaintext.conf:/usr/share/logstash/pipeline/logstashplaintext.conf
      - ./logstashplaintext.conf:/usr/share/logstash/pipeline/logstashhighfiveapp.conf
    environment:
      - LOGSTASH_PORT=5016
      - LOGSTASH_PLAINTEXT_PORT=5098
      - LOGSTASH_HIGHFIVEAPP_PORT=5099
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=powershell
      - XPACK_MONITORING_ENABLED=false
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "5016:5016"  
      - "5000:5000"  
      - "9600:9600"  
      - "5099:5099" 

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "xpack.security.enabled=false"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  es-data:
    driver: local